// <auto-generated />
using Auction.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auction.Migrations.Lot
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190605112615_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auction.Models.Lot", b =>
                {
                    b.Property<int>("LotID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LotOwner")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LotUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Lotname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Lotprice")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("LotID");

                    b.ToTable("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
